# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: right_arm
  joint_model_group_pose: right_home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base_link_to_human_head
    - camera_joint
    - hokuyo_joint
    - left_forearm_to_base_linkRoll
    - left_forearm_to_base_linkPitch
    - left_forearm_to_base_linkYaw
    - left_arm_to_forearm
    - left_hand_to_arm_yaw
    - left_hand_to_arm_pitch
    - left_hand_to_arm_roll
    - left_thigh_to_base_linkYaw
    - left_thigh_to_base_linkRoll
    - left_thigh_to_base_link
    - left_leg_to_left_thigh
    - left_leg_to_left_ankle
    - left_foot_to_left_ankle
    - aux_joint_l
    - right_forearm_to_base_linkRoll
    - right_forearm_to_base_linkPitch
    - right_forearm_to_base_linkYaw
    - right_arm_to_forearm
    - right_hand_to_arm_yaw
    - right_hand_to_arm_pitch
    - right_hand_to_arm_roll
    - right_thigh_to_base_linkYaw
    - right_thigh_to_base_linkRoll
    - right_thigh_to_base_link
    - right_leg_to_right_thigh
    - right_leg_to_right_ankle
    - right_foot_to_right_ankle
    - aux_joint_r
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []